### ISSUE TITLE
The ending of this video is deeply unsatisfactory. 

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/sinatra-video-review-building-a-site-generator-part-2#1]
Honestly, I can't say I'm even sure why this video (and the prior) were included in this section at the place that they were, or at all. The main concepts that appeared to be covered were 

-- a more primitive/founational use of ERB than the one covered in the Sinatra unit
-- a more foundational/primitive way to create a website than the one covered in the Sinatra unit

Neither of the topics were a review, both were new topics. Didn't really seem to relate to MVC even though there were flashes of it...

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We will review the ordering and content of the videos.

As always thank you for contributing.
