### ISSUE TITLE
Suggested summary and learning objectives

### ISSUE THREAD

**Issue by youssefmys** [learn-co-curriculum/sinatra-video-review-building-a-site-generator-part-2#2]
**Suggested summary** 

In this video,  more light will be  shed on using embedded ruby (ERB) and binding concept for dynamic generation of playlister project website outside routes of Sinatra . The video lesson will discuss generation of ERB templates, injection of ruby code into HTML strings, and using a valid ruby variables within ERB view files.   

**Suggested learning objectives**

- Using ERB ruby gem for dynamic generation of views from template files.
- Clarifying the concept of binding and loading of local variables into ERB files.
- Applying ERB for generation of  HTML interface of playlister project.
- Manipulation of files and paths using embedded ruby  libraries.

**Comment by curiositypaths** [comment]
Thank you for submitting your suggested summary and objectives.
