### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by sjmoody** [learn-co-curriculum/sinatra-video-review-building-a-site-generator-part-2#3]
Summary:
In part 2 of this video, Avi walks through how to generate a large static site from page templates, related models, and a one file method to tie them together.  This is a good precursor to the magic of Sinatra, as you'll see how to produce the static equivalent of a Sinatra site.  

Objectives:
* Use a heredoc to write multi-line html within ruby
* Understand the difference between an erb file and an html file
* Use binding to pass a local variable to an HTML page
* Feel the pain of Avi debating whether to refactor sandwich code using a contrived example :)

**Comment by curiositypaths** [comment]
Thank you for submitting your suggested summary and objectives.
