### ISSUE TITLE
Placement of videos

### ISSUE THREAD

**Issue by sjmoody** [learn-co-curriculum/sinatra-video-review-building-a-site-generator-part-2#4]
The content of this video is superficially the same as the latest projects (music library site generator) but the actual content is more suitable to learn before Sinatra.  I don't think this video would have helped with any previous projects, however seeing it before the Sinatra concepts might have made for a nice introduction to erb and dynamic webpage content.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We will review the ordering of these videos.

As always thank you for contributing.
