### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/sinatra-video-review-building-a-site-generator-part-2#5]
_Suggested Summary_
- In part 2 of this two part video lecture, Avi goes over templating (and specifically, _ERB_) to show how we can have a single view and then dynamically update the information in that view for each of a collection of objects (such as, _artists_, _songs_, and _genres_).

_Suggested Objectives_
- Introduce the concept of _templating_, which allows you to inject Ruby code into an HTML template to make it dynamic.
- Explain the Ruby keyword _binding_ and what it does. Utilize _binding.pry_ as an example and show how _binding_ makes _binding.pry_ possible.
- Develop the ability to recognize _sandwich patterns_ and refactor them using the keyword _yield_.

**Comment by curiositypaths** [comment]
Thank you for submitting your suggested summary and objectives.
