### ISSUE TITLE
Building a Site Generator - What is the Goal Here?

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/sinatra-video-review-building-a-site-generator-part-2#6]
These two videos, as many before, were incredibly frustrating, as they didn't seem to be in the right place at all. There are new topics that are thrown in without explanation (should we already know this?), and code I have been learning to write for half of the program is now apparently "bad code". Yet there are views with logic written in them that a coach just told me yesterday was a very bad habit to get into and it would not pass.

As I watch this, I'm not sure anymore how I am supposed to be setting up my application. There are so many conflicting lessons.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We will review the ordering and content of the videos in this section.

As always thank you for contributing.
