### ISSUE TITLE
Feedback on these review videos

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/sinatra-video-review-building-a-site-generator-part-2#8]
I may be the only one but I didn't feel that these videos were useful at all. They didn't appear to be closely related to the labs we've been working on. There wasn't any context leading up to them either so I could know what exactly Avi was working on and where he was in that particular project. There were also a lot of new concepts introduced and I don't know if I'm supposed to take notes on them for future use. Basically, it felt like an out of place video excerpt. Was there something I missed here?

**Comment by cjbrock** [comment]
Thank you providing feedback. We're always looking for ways to improve our curriculum. You're not the only student who has provided this feedback, and we're discussing how to make this a better experience for the students. Thank you for taking your time to make Learn a better place.
 // Corinna 💙
